baseURL = 'https://blog.withsam.org'
languageCode = 'en-us'
title = "Sam's blog"
theme = 'blist'

[languages]
  [languages.en]
    contentDir = "content"
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Sam"
      introSubtitle = "24 y/o developer who enjoys cyber security, blogging and strategy games"
      introPhoto = "/picture.jpg"
      logo = "/logo.png"
      reading_speed = 114

    [[languages.en.menu.main]]
        name = "Posts"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[params]
  darkModeToggle = true

  enableSearch = true
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

[params.homepage.social]
  title = "Links"

  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/udf"

[[menu.main]]
  name = "About"
  url = "/about"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true
